### PR TITLE
Feature request: return currentZoomed variable

### PR DESCRIPTION
**Pull request by rantuma**
#19
Not tested!

### CODE REVIEW

**Comment by jarvisniu** [comment]
Thanks for your contribution!
But there is no need to add a method to get a Vue data value. The Vue data is also **public**.
You can just use `this.$refs.zoomer.currentZoomed` to get the value.

Furthermore, there is another tip: the data/prop/method names can't be same.
So if you really want to add one, you should name it `getCurrentZoomed`.

**Comment by rantuma** [comment]
Both points are good to know, thank you for that! 
`this.$refs.zoomer.currentZoomed` always returns 'undefined' and `this.$refs.zoomer.zoomed` always returns 'false' regardless of whether it is zoomed in or not. 
Do you maybe know how to get the wanted boolean?

**Comment by jarvisniu** [comment]
For `<v-zoomer-gallery ref="zoomer">`, use `this.$refs.zoomer.currentZoomed`.
For `<v-zoomer ref="zoomer">`, use `this.$refs.zoomer.scale !== 1` as the equivalent.

**Comment by rantuma** [comment]
I am not using the gallery, so I need to use `this.$refs.zoomer.scale !== 1` . 
Thank you!

**Comment by rantuma** [comment]
FYI:
`this.$refs.zoomer.scale` didn't work always. Sometimes, I had to use `this.$refs.zoomer[0].scale`
I am interested in why this is.

**Comment by jarvisniu** [comment]
Because you are using gallery. For that case, you should use `.currentZoomed`, not `.scale`.

In order to eliminate the confusion, I recommend to distinguish the two ref names:

For `<v-zoomer-gallery ref="gallery">`, use `this.$refs.gallery.currentZoomed`
For `<v-zoomer ref="zoomer">`, use `this.$refs.zoomer.scale !== 1`

**Comment by rantuma** [comment]
I am not using `v-zoomer-gallery>`, but `<v-zoomer>`
The actual code: 
`
                <v-zoomer ref="VueZoomerRef" class="VueZoomerStyle">
                  
                </v-zoomer>
`
Then, `this.$refs.VueZoomerRef.scale` returns `undefined` and `this.$refs.VueZoomerRef[0].scale` the actual scale..
I also tried to change the `${entry.imgsrc}` to a non-linked value. For example `:src="require(`../assets/moi.png`)"` Same happened.

**Comment by jarvisniu** [comment]
OK, may be you are using `v-for` on `<v-zoomer>` ?

If then, the ref will become an array.  And you'd better use`<v-zoomer-gallery>` in this case.

**Comment by rantuma** [comment]
That's true, I am using `v-for` to go 'through' the content of an table. 
Good to know where it comes from, thank you.

**Pull request closed without merging**
